server:
  port: 8002

spring:
  application.name: demo
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: mongo-1
  security:
    oauth2:
      client:
        registration:
          mongo-1:
            provider: keycloak-idp
            client-id: mongo-1
            client-secret: 7UxCcmk6hUT8zBIfGCJlSVopiqziAyKe
            authorization-grant-type: client_credentials
          mongo-2:
            provider: keycloak-idp
            client-id: mongo-2
            client-secret: 5qDvQlTDRHss46QwEjmGS2hA7hlAHy9c
            authorization-grant-type: client_credentials
        provider:
          keycloak-idp:
            token-uri: http://localhost:8090/realms/mongo/protocol/openid-connect/token

logging:
  level:
    web: DEBUG
    com.example.webui.client.MongoUserClient: DEBUG