server:
  port: 8001
spring:
  application.name: mongo-user
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: example
      username: root
      password: password


logging.level:
  org.springframework.data.mongodb: DEBUG
